language: node_js
node_js:
  - "7"
  - "6"
cache:
  - directories:
    - node_modules
env:
- NODE_ENV=test
script:
  - npm run test
after_script:
  - npm run test --coverage --coverageReporters=coverage/text-lcov | coveralls
