language: node_js
node_js:
  - "7"
  - "6"
cache:
  - directories:
    - node_modules
env:
- NODE_ENV=test
before_install:
- npm prune
install:
- npm install
script:
  - npm run test
after_script:
  - cat ./coverage/lcov.info | npx coveralls
